### ISSUE TITLE
"chessli tactics ankify" always tells me I have no puzzles

### ISSUE THREAD

**Issue by nayyala** [pwenker/chessli#12]
I ran "chessli tactics ls" and was able to print the table of puzzles

I also did some puzzles in lichess before running the command

However, running "chessli tactics ankify" always tells me I have no new puzzles. I've even tried running it for a handful of users and even with the --all flag.

**Comment by pwenker** [comment]
Hey, thanks for opening up this issue! I found the issue, and I'm going to fix it later this day and update the version so you can download it! Sorry for the bug and thanks for reporting :)

**Comment by pwenker** [comment]
Fixed in v0.2.2. 
You can update with `pip install --upgrade chessli`(:
