### ISSUE TITLE
Cannot ankify mistakes and games sequentially from last-time due to shared tag

### ISSUE THREAD

**Issue by nayyala** [pwenker/chessli#16]
When i do
chessli games ankify

I cannot then run the above command for opening since the last-time stamp is updated and tells me I have no new games to fetch

**Comment by pwenker** [comment]
Hey, good catch! This is now fixed with v0.2.3. If you installed chessli with `pip` you can do `pip install --upgrade chessli` to get the new working version. 

Chessli now creates two independent time stamps, one for games and one for openings.
