### ISSUE TITLE
Totally new programmer 

### ISSUE THREAD

**Issue by Maryjezek** [pwenker/chessli#17]
Does anyone know why I get this error message when I try to enter the command: I'm using Python 3.9
>>> py -m pip --version

I get the message File "<stdin>", line 1

SyntaxError: invalid syntax

Thank you for any help!

**Comment by ExtremeCoolDude** [comment]
You should enter that command **not** in the python interactive shell, but in command terminal.  In Linux bash terminal, you should enter full `python -m pip --version` or it will say py command not found.

**Comment by pwenker** [comment]
@Maryjezek, can I close this issue, or do you still have problems?

**Comment by Maryjezek** [comment]
Yes Please close it! Thanks!
