### ISSUE TITLE
how do i get this to work on anki?

### ISSUE THREAD

**Issue by marksteadman080592** [pwenker/chessli#20]
how do i get this to work on anki?

**Comment by pwenker** [comment]
Your question is kind of broad, but I guess this link should help you: https://pwenker.com/chessli/tutorial/how_to_set_up_chessli/#anki-support-via-apy

There are two ways: 
1) Either you export your openings/mistakes/tactics as `csv` file (that's just a special text file) and then you can import it into anki as described in the manual here: https://apps.ankiweb.net/docs/manual20.html#importing
2) Or you use the tool `apy` to directly import them into anki. 

You also need to have a fitting anki card template, e.g., as explained here: https://pwenker.com/chessli/tutorial/how_to_set_up_chessli/#getting-chesslis-anki-cards-templates
