### ISSUE TITLE
Minor tactics cards (bug?)

### ISSUE THREAD

**Issue by Aguscarpio** [pwenker/chessli#22]
Tactics anki cards ask me to make both white and black moves. How to solve it?

**Comment by pwenker** [comment]
That's strange. I cannot reproduce that bug. Which anki cards are you using?

**Comment by pwenker** [comment]
If you are using a newer version of the following card templates (or a derivative of them): https://github.com/TowelSniffer/Anki-Chess-2.0 then your problem might result from the new feature introduced here: https://github.com/TowelSniffer/Anki-Chess-2.0/releases/tag/1.2.2 which allows to play all moves. In that case you should have a `playAllMoves` field which you need to leave empty on all cards where you only want to play your own moves.
