### ISSUE TITLE
Can't make moves 

### ISSUE THREAD

**Issue by amalrajjs** [pwenker/chessli#29]
Instead of moves for Sicilian 1.e4 e5 2.Nf3 Nc6, there is an alternative way e2e4 e7e5 g1f3 b8c6. Please add this features to chessli.

**Comment by amalrajjs** [comment]
Moves are in UCI format. Can you add the feature to support UCI?

**Comment by jpfreiire** [comment]
i can't install chessli, if anyone can help me please contact me on discord pls flex[#3045](https://www.youtube.com/hashtag/3045)
