### ISSUE TITLE
i can't install chessli, if anyone can help me please contact me on discord pls flex#3045

### ISSUE THREAD

**Issue by jpfreiire** [pwenker/chessli#30]
Hi guys I'm not very good with python and I couldn't install chessli, if anyone can make an explanatory video or send me a message on discord flex#3045
pls :(

**Comment by jpfreiire** [comment]
The installation method is in English, and as I'm Brazilian I don't understand much because my native language is Portuguese

**Comment by pwenker** [comment]
Bom dia! 
Infelizmente nao e muito facil instalar o chessli sem saber como programar. ou como funciona Python. Eu duvido que uma traducao da documentacao em portugues ajudaria muito...
Mas eu estou pensando em criar um "novo chessli" que voce poderia usar sem instalar nada e sem saber programar (um web-app). 
Nao tenho muito tempo atualmente, mas como muitas pessoas tem problemas instalar e usar o chessli desta forma, eu vou tentar. 
Vc acha que um web app seria melhor?

**Comment by pwenker** [comment]
Bom dia! So queria dizer que estou finalizando o web-app agora, entao vou fechar esse issue aqui!
