### ISSUE TITLE
installation issue - wsl

### ISSUE THREAD

**Issue by avnav0** [pwenker/chessli#31]
tried installing on wsl with `pip install chessli`

got: `Could not install packages due to an EnvironmentError: [Errno 28] No space left on device`

so, i used `export TMPDIR='/var/tmp'` and the install completed.  it's now in the `site-packages` file for python.

however, if try to run `chessli` or any variation on cli, it tells me: `-bash: chessli: command not found`

**Comment by pwenker** [comment]
Hey, I am currently develping a new simplified version of chessli with a graphical user interface. 
Therefore, it will no longer be necessary to install the package yourself and this issue should go away.
