### ISSUE TITLE
broken url on ankiweb

### ISSUE THREAD

**Issue by KamarajuKusumanchi** [pwenker/chessli#36]
https://pwenker.com/chessli/tutorial/how_to_set_up_chessli/#getting-chesslis-anki-cards-templates links to https://ankiweb.net/shared/info/829523972 which says

NOTE: You need to add the following media files https://github.com/TowelSniffer/Anki-Chess-2.0/tree/main/Media%20Files to your anki collection media folder as described here: https://ankiweb.net/shared/info/1082754005.

However https://ankiweb.net/shared/info/1082754005 is giving "This shared item is missing or currently unavailable."

Could you please fix it?

thanks
raju

**Comment by pwenker** [comment]
Hey Raju, thank you for reaching out. :)

I am currently developing a  new simplified version of chessli with a graphical user interface. 

Your issue will become obsolete. I'll update you as soon as it is finished.
