### ISSUE TITLE
Error: requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url

### ISSUE THREAD

**Issue by pwenker** [pwenker/chessli#4]
Ported from reddit for posteriority.

I seem to be running into an issue fetching the games:
Input:
```
:~/chess/chessli$ chessli --user <name of the user> games ankify
```
Output:
```
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://lichess.org/api/games/user/<name of the user>?since=1611013425256&max=20
```

**Comment by pwenker** [comment]
This seems to be related to the Lichess API Authentification.  (Some parts of the lichess API, for example fetching your puzzle activity, require authentification.)
Can you please try out the following?

- Create a personal API access token: https://lichess.org/account/oauth/token/create
- Put your token into a file in the `configs` folder with the name `lichess.token`.
- Please keep this token safe and private so it can not be misused by other people.

Does that solve the problem?

**Comment by ljump12** [comment]
That solved the issue, thanks.

**Comment by pwenker** [comment]
Happy to hear :)
